### ISSUE TITLE
sagej.cls not available when rendering to pdf

### ISSUE THREAD

**Issue by michaelgfalk** [chrishanretty/sagej_quarto#1]
If you add the template to the project using the `quarto add` method, the `quarto render` throws an error, "unable to find sagej.cls".

The problem can be fixed by adding the following to `_extension.yml`:

```
contributes:
  formats:
    pdf:
      format-resources:
        - sagej.cls
```

This copies sagej.cls to the working directory during the render.
