### ISSUE TITLE
Undefined control sequence for `pandocbounded`

### ISSUE THREAD

**Issue by e-kotov** [chrishanretty/sagej_quarto#2]
```
Undefined control sequence.
l.399 \pandocbounded
                    {\includegraphics[keepaspectratio]{sage_files/figure-pdf... 

see sage/sage.log for more information.
```

Getting this even with the default example that comes with the template.

Here a solution is suggested:
https://github.com/Wandmalfarbe/pandoc-latex-template/issues/391#issuecomment-2359834831

Therefore this can be fixed with

```
format:
  sagej-pdf:
    keep-tex: true
    classoption: [Afour,times,sageh]
    header-includes:
      - \newcommand{\pandocbounded}[1]{#1}
```

For reference:
- I am on macOS 15.2 (arm)
- `quarto --version`: 1.6.39
- `pandoc --version`: pandoc 3.6.1, Features: +server +lua, Scripting engine: Lua 5.4
